language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
  - npm install -g serverless
  - npm install
script:
  - npm test
  - sls deploy 
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e2a463f83bee_key -iv $encrypted_e2a463f83bee_iv -in PokerDisclosure-fdc6a42b4db5.json.enc -out PokerDisclosure-fdc6a42b4db5.json -d