language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
env:
  - GOOGLE_APPLICATION_CREDENTIALS=PokerDisclosure-fdc6a42b4db5.json
install:
  - npm install -g serverless
  - npm install
script:
  - npm test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e2a463f83bee_key -iv $encrypted_e2a463f83bee_iv -in PokerDisclosure-fdc6a42b4db5.json.enc -out PokerDisclosure-fdc6a42b4db5.json -d
deploy:
  - provider: script
    script:
      - sls deploy
    skip_cleanup: true
    on:
      branch: master
after_success: npm run coveralls
